name: keyboard_utils_fork
description: fork from https://github.com/IsaiasSantana/keyboard_utils
version: 1.1.0
homepage: https://github.com/heartsradiant/keyboard_utils.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.keyboard_utils
        pluginClass: KeyboardUtilsPlugin
      ios:
        pluginClass: SwiftKeyboardUtilsPlugin
